/**
 * Youtube-appLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Error400SingleString
 */
interface Error400SingleString {
  message: string;
}

export class Error400SingleStringError extends ApiError<Error400SingleString> {}
