/**
 * Youtube-appLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Error400
 */
interface Error400 {
  code: number;
  message: string;
}

export class Error400Error extends ApiError<Error400> {}
