/**
 * Youtube-appLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { passThroughInterceptor } from './core';
import { AuthenticatorInterface } from './core';

/** None authentication provider */
export const noneAuthenticationProvider = () => passThroughInterceptor;

export const customQueryAuthenticationProvider = ({
  key,
}: {
  key: string;
}): AuthenticatorInterface<boolean> => {
  return (requiresAuth?: boolean) => {
    if (!requiresAuth) {
      return passThroughInterceptor;
    }

    return (request, options, next) => {
      request.url +=
        (request.url.indexOf('?') === -1 ? '?' : '&') +
        encodeQueryParams({ key: key })
      return next(request, options);
    };
  };
};
function encodeQueryParams(queryParams: Record<string, string>) {
  let queryString = [];
  for (let key of Object.keys(queryParams)) {
    queryString.push(
      `${encodeURIComponent(key)}=${encodeURIComponent(queryParams[key])}`
    );
  }
  return queryString.join('&');
}

